apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-keyvault-composition
  labels:
    crossplane.io/xrd: xkeyvaults.runtime.cariad.net
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: runtime.cariad.net/v1alpha1
    kind: XKeyVault
  writeConnectionSecretsToNamespace: upbound-system
  resources:
  - name: keyvault-1
    base:
      apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
      kind: Vault
      spec:
        forProvider:
          enabledForDiskEncryption: true
          location: West US
          purgeProtectionEnabled: false
          resourceGroupName: replaced-by-patches
          skuName: standard
          softDeleteRetentionDays: 7
          tenantId: 2d8cc149-4c57-462b-a1fb-6e548ffd73bd
          tags: # (Optional) A mapping of tags to assign to the resource.
            environment: dev # replaced-by-params
        writeConnectionSecretToRef:
          namespace: replaced-by-patches #replaed by patches
          name: replaced-by-patches #replaed by patches
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-connection"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.providerConfigRef.name
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.resourceGroup
      toFieldPath: spec.forProvider.resourceGroupName
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
      transforms:
      - type: map
        map:
          us-west: West US
          us-east: East US
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.environment
      toFieldPath: spec.forProvider.skuName
      transforms:
      - type: map
        map:
          dev: standard
          stage: standard
          prod: premium
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.environment
      toFieldPath: spec.forProvider.tags.environment
    connectionDetails:
    - type: FromFieldPath
      name: uri
      fromFieldPath: status.atProvider.vaultUri
  - name: accesspolicy
    base:
      apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
      kind: AccessPolicy
      metadata:
        name: residency-vaultpolicy
      spec:
        forProvider:
          keyVaultIdSelector:
            matchControllerRef: true

          keyPermissions:
            - Get
            - Create
            - Delete
            - List
          tenantId: 2d8cc149-4c57-462b-a1fb-6e548ffd73bd
          objectId: 90d1c7df-0395-40e9-96a8-3b8cfbf65ce2
          certificatePermissions:
            - Get
            - GetIssuers
            - Create
            - SetIssuers
            - Delete
            - DeleteIssuers
            - List
            - ListIssuers
          secretPermissions:
            - Get
            - Set
            - Delete
            - List
          storagePermissions:
            - Get
            - Set
            - Delete
            - List
            - SetSAS
            - GetSAS
            - DeleteSAS
            - RegenerateKey
        providerConfigRef:
          name: wireless-car
    patches:
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.providerConfigRef.name
      policy:
        fromFieldPath: Required
