apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-network-composition
  labels:
    crossplane.io/xrd: xnetworks.runtime.cariad.net
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: runtime.cariad.net/v1alpha1
    kind: XNetwork
  writeConnectionSecretsToNamespace: upbound-system
  resources:
  - name: dnszone
    base:
      apiVersion: network.azure.jet.crossplane.io/v1alpha1
      kind: DNSZone
      metadata:
        name: residency-dnszone-demo
      spec:
        forProvider:
          # name: residencydemo.vwac.net # patched
          resourceGroupName: dev-mod-accenture-crossplane-rg # patched
        providerConfigRef:
          name: wireless-car # patched
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.providerConfigRef.name
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.resourceGroup
      toFieldPath: spec.forProvider.resourceGroupName
