apiVersion: runtime.cariad.net/v1alpha1
kind: Function
metadata:
  name: residency-function
  annotations:
    # must not have uppercase or any special symbols 
    # Only alphanumeric, no special characters allowed. Limit the function name to 32 characters to avoid naming collisions. For more information: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftweb
    crossplane.io/external-name: residencyfunctiondemo
spec:
  parameters:
    location: us-west
    resourceGroupName: dev-mod-accenture-crossplane-rg
    environment: dev # choose from dev, stage, prod (if prod, then Tier is Premium)
  compositionSelector:
    matchLabels:
      provider: azure
  writeConnectionSecretToRef:
    name: residency-function-conn